export default {
  country:'CountryScreen',
  login: 'Login',
  registration: 'Registration',
  forgetPassword: 'ForgetPassword',
  dashboard: 'DashboardScreen',
  cashWalletHistory: 'CashwallethistoryScreen',
  spendingWalletHistory: 'SpendingwallethistoryScreen',
  productVoucherHistory: 'ProductvoucherhistoryScreen',
  pairBonus: 'PairbonusScreen',
  unilevelBonus: 'UnilevelbonusScreen',
  indirectBonus: 'IndirectbonusScreen',
  stockistBonus: 'StockistbonusScreen',
  directTeam: 'DirectteamScreen',
  balanceRequest: 'BalancerequestScreen',
  cashoutRequest: 'CashoutrequestScreen',
  unilevelWithdraw: 'UnilevelwithdrawScreen',
  balanceTransfer: 'BalancetransferScreen',
  walletConversation: 'WalletConversation',
  userProfile: 'UserProfile',
  announcement: 'Announcement',
  contactUs: 'ContactUs',
  tabBar: 'TabBar',
  welcome: 'Welcome',
  home: 'Home',
  productVoucherRequest: 'ProductVoucherRequest',
  drawer: 'Drawer',
  report: 'Report',
  RepurchasesummaryScreen: 'RepurchasesummaryScreen',
  myOrders: 'MyOrders',
  orderDetail: 'OrderDetail',
  sponserDetail: 'sponserDetail',
  businessRegistration: 'BusinessRegistration',
  registrationPaymentSuccess: 'RegistrationPaymentSuccess',
  businessRepurchase: 'BusinessRepurchase',
  welcomeRepurchase: 'WelcomeRepurchase',
  regionSelection: 'RegionSelection',
  repurchaseCategorySelection: 'RepurchaseCategorySelection',
  repurchaseProductSelection: 'RepurchaseProductSelection',
  repurchasePurchaseBill: 'RepurchasePurchaseBill',
  repurchasePaymentSuccess: 'RepurchasePaymentSuccess',
  businessUpgrade: 'BusinessUpgrade',
  upgradePaymentSuccess: 'UpgradePaymentSuccess',
  unilevalMonthlySalery: 'UnilevalMonthlySalery',
  stockistRetailHistory: 'StockistRetailHistory',
  privacyPolicy: 'PrivacyPolicy'
};

// export default {
//   login: 'Login',
//   registration: 'Registration',
//   forgetPassword: 'ForgetPassword',
//   dashboard: 'DashboardScreen',
//   cashWalletHistory: 'CashwallethistoryScreen',
//   spendingWalletHistory: 'SpendingwallethistoryScreen',
//   productVoucherHistory: 'ProductvoucherhistoryScreen',
//   pairBonus: 'PairbonusScreen',
//   unilevelBonus: 'UnilevelbonusScreen',
//   indirectBonus: 'IndirectbonusScreen',
//   stockistBonus: 'StockistbonusScreen',
//   directTeam: 'DirectteamScreen',
//   balanceRequest: 'BalancerequestScreen',
//   cashoutRequest: 'CashoutrequestScreen',
//   balanceTransfer: 'BalancetransferScreen',
//   walletConversation: 'WalletConversation',
//   userProfile: 'UserProfile',
//   leadershipAndRanking: 'LeadershipAndRanking',
//   support: 'Support',
//   tabBar: 'TabBar',
//   welcome: 'Welcome',
//   home: 'Home',
//   productVoucherRequest: 'ProductVoucherRequest',
//   drawer: 'Drawer',

//   sponserDetail: 'sponserDetail',
//   businessRegistration: 'BusinessRegistration',
//   registrationPaymentSuccess: 'RegistrationPaymentSuccess',
//   businessRepurchase: 'BusinessRepurchase',
//   welcomeRepurchase: 'WelcomeRepurchase',
//   regionSelection: 'RegionSelection',
//   repurchaseCategorySelection: 'RepurchaseCategorySelection',
//   repurchaseProductSelection: 'RepurchaseProductSelection',
//   repurchasePurchaseBill: 'RepurchasePurchaseBill',
//   repurchasePaymentSuccess: 'RepurchasePaymentSuccess',
//   businessUpgrade: 'BusinessUpgrade',
//   upgradePaymentSuccess: 'UpgradePaymentSuccess',
// };
