export default {
  login: "Login",
  loginSubtext: "You must be a registered\nmember to be able to login",
  userId: "User ID",
  password: "Password",
  somethingWentWrong: "Something went wrong",
  userIdRequired: "* User Id is required.",
  passwordRequired: "* Password is required.",
  signIn: "Sign In",
  forgetPassword: "Forget Password",
  forgetPasswordSubText: "Please enter user id and email \nto reset passsword",
  email: "Email",
  continue: "Continue",
  emailRequired: "* Email is required.",
  screenTitles: {
    dashboard: "Dashboard",
    directMembers: "Direct Members",
    balanceRequest: "Balance Request",
    cashoutRequest: "Cashout Request",
    unilevelWithdrawRequest: "Unilevel Request",
    unilevelWithdrawHistory: "Unilevel Withdraw History",
    balanceTransfer: "Balance Transfer",
    productVoucherRequest: "Product Voucher Request",
    repurchasesummary: "Repurchase Summary",
    myOrders: "My Orders",
    business: "Business",
    register: "Register",
    upgrade: "Upgrade",
    repurchase: "Repurchase",

    //Report
    balanceRequestReport: "Balance Request Report",
    productVoucherReport: "Product Voucher Report",
    pairBonusHistory: "Pair Bonus History",
    sponserBonusHistory: "Sponser Bonus History",
    upgradeBonusHistory: "Upgrade Bonus History",
    unilevelBonusHistory: "Uni-Level Bonus History",
    indirectBonusHistory: "Indirect Bonus History",
    selfUniLevelBonusHistory: "Self-Uni Level Bonus History",
    leadershipBonusHistory: "Leadership Bonus History",
    leadershipPoolBonusHistory: "Leadership Pool Bonus History",
    cashWalletHistory: "Cash Wallet History",
    spendingWalletHistory: "Spending Wallet History",
    productWalletHistory: "Product Wallet History",
    stockistBonusHistory: "Stockist Bonus History",
    unilevalMonthlySalery: "Unilevel monthly salary",
    stockistRetailHistory: "Stockist Retail History",

    //for tabbar
    WalletConversation: "Wallet Conversation",
    UserProfile: "User Profile",
    Announcement: "Announcement",
    contactUs: "ContactUs",
    Home: "Dashboard",
  },
  welcomeToFaforlife: "Welcome To Farforlife",
  walletBalance: "Wallet Balance",
  cashout: "Cashout",
  transfer: "Transfer",
  genealogy: "Genealogy",
  rankingLeftPV: "Ranking Left PV",
  rankingRightPV: "Ranking Right PV",
  pairingLeftPV: "Pairing Left PV",
  pairingRightPV: "Pairing Right PV",
  totalUpgradePV: "Total Upgrade PV",
  packageAmount: "Package Amount",
  cashWalletPoint: "Cash Wallet Point",
  pairBonusPoint: "Pair Bonus Point",
  productVoucherWallet: "Product Voucher Wallet",
  unilevelWallet: "Unilevel Wallet",
  placementBonusPoint: "Placement Bonus Point",
  stockistRetailBonus: "Stockist Retail Bonus",
  totalIndirectBonus: "Total Indirect Bonus",
  leadershipPoolBonus: "Leadership Pool Bonus",
  totalEarnings: "Total Earnings",
  travelAwardPvGrop: "Travel Award Pv - Grop",
  travelAwardPvPersonal: "Travel Award Pv - Personal",
  leftEp: "LEFT EP",
  rightEp: "RIGHT EP",
  personalEp: "PERSONAL EP",
  welcome: "Welcome",
  welcomeMsg:
    "We Are Providing Organic Health Solutions To Life Threatening Disease, Helping Our Members Discover Healthy Lifestyle And Achiveing Wealth In The Process",
  history: "History",
  spendingWalletBalance: "Spending Wallet Balance",
  note: "Note",
  cashoutNote:
    "Local Banks Payment To Countries\nOutside Nigeria Attracts High Bank Charges!",
  account: "Account",
  paymentMethod: "Payment Method",
  withdraw: "Withdraw",
  enterAmount: "Enter Amount",
  enterWithdrawAmount: "Enter Withdrawal Amount",
  availableBalance: "Available Balance",
  transactionAmount: "Transaction Amount",
  remark: "Remark",
  uploadReceipt: "Upload Receipt",
  chooseFile: "Choose File",
  noFileChosen: "No File Chosen",
  submit: "Submit",
  paymentDate: "Payment Date",
  leadershipRankAndAchivements: "LEADERSHIP RANKS &\nACHIEVEMENTS",
  achieved: "ACHIEVED",
  inProgress: "IN PROGRESS",
  enterAmount: "Enter amount",
  enterTransactionAmount: "Enter transaction amount",
  enterRemark: "Enter Remark",
  pleaseEnterAmount: "Please enter amount",
  pleaseSelectDate: "Please select date",
  pleaseEnterTransactionAmount: "Please enter transaction amount",
  pleaseEnterRemark: "Please enter remark",
  selectWallet: "Select Wallet",
  convert: "Convert",
  online: "Online",
  sponserId: "Sponser ID :",
  placementId: "placement ID :",
  mobile: "Mobile :",
  transactionPassword: "Transaction Password :",
  txnPassword: 'Transaction Password',
  enterTxnPassword: 'Enter Transaction Password',
  joiningDate: "Joining Date :",
  status: "Status :",
  activateDate: "Activate Date :",
  myCurrentPackage: "My Current Package :",
  pleaseSelectWallet: "Please Select Wallet",
  active: "Active",
  country: "country :",
  myReason: "My Reason :",
  myTeam: "My Team",
  faforlife: "FAFORLIFE",
  pairingBonus: "Pairing Bonus",
  sponserBonus: "Sponser Bonus",
  upgradeBonus: "Upgrade Bonus",
  uniLevelBonus: "Uni-Level Bonus",
  indirectBonus: "Indirect Bonus",
  selfUniLevelBonus: "Self-Uni Level Bonus",
  leadershipBonus: "Leadership Bonus",
  unilevalMonthlySalery: "Unilevel monthly salary",
  leadershipPoolBonus: "Leadership Pool Bonus",
  requestDate: "Request Date",
  amount: "Amount",
  remarks: "Remarks",
  status: "Status",
  date: "Date",
  income: "Income",
  cashWallet: "Cash Wallet",
  refferID: "Reffer ID",
  level: "Level",
  type: "Type",
  fromDate: "From Date",
  toDate: "To Date",
  requestType: "Request Type",
  name: "Name",
  mobileNo: "Mobile",
  joiningDatePlain: "Joining Date",
  orderId: "Order Id",
  orderType: "Order Type",
  orderDate: "Order Date",
  viewDetails: "View Details",
};
