export default {
  bgFull: require('../assets/images/background2.jpg'),
  bgBottom: require('../assets/images/background.jpg'),
  crown: require('../assets/images/crown.png'),
  diamond: require('../assets/images/diamond.png'),
  director: require('../assets/images/director.png'),
  gold: require('../assets/images/gold.png'),
  leaderHead: require('../assets/images/leadership_rank.png'),
  logo: require('../assets/images/logo.png'),
  menuBar: require('../assets/images/menu-bar.png'),
  ruby: require('../assets/images/ruby.png'),
  sliver: require('../assets/images/sliver.png'),
  star: require('../assets/images/star.png'),
  ambassador: require('../assets/images/ambassador.png'),
  userPlaceholder: require('../assets/images/user.png'),
  dashboardBg: require('../assets/images/dashboardBg.jpeg'),
  walletCircle: require('../assets/images/wallet-circle.png'),
  welcomeBg: require('../assets/images/welcomeBg.jpg'),
  logoWithBg: require('../assets/images/logoWithBg.png'),
  cashoutBg: require('../assets/images/cashoutBg.png'),
  balanceBg: require('../assets/images/balanceBg.png'),
};
